### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by WiredWonder** [Go-Shippit/Woo-Commerce#5]
Hi guys,

woocommerce-shippit.php is showing 1.5.5 in this repo but the version on the Wordpress Plugin store is 1.5.6 - are you able to make sure you've merged your latest changes?

Thanks,
Jason

**Comment by WiredWonder** [comment]
Hey @hardik-mamis hope you are well. Are you able to push 1.6.1 to this repo so I can update my fork? Thanks :)

**Comment by WiredWonder** [comment]
@matthew-muscat are you able to push 1.6.4? Thanks :)

**Comment by matthew-muscat** [comment]
@galapogos01 — confirming that v1.6.4 is now available over at https://github.com/Go-Shippit/Woo-Commerce/releases/tag/v1.6.4
