### ISSUE TITLE
HPOS compatibility

### ISSUE THREAD

**Issue by WiredWonder** [Go-Shippit/Woo-Commerce#9]
Hi guys,

Do you have a roadmap to making this plugin HPOS compliant?

https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#declaring-extension-incompatibility

It looks as simple as fixing up some of the post_meta calls to use $order-> methods.

**Comment by matthew-muscat** [comment]
Hi @galapogos01 

We don't have this feature on the roadmap, however if you have a merchant that requires these capabilities we can certainly look into it.

Best thing would be to raise a support ticket with our team so we can get our product team across this (feel free to reference this github issue).

On a related note — there's some items on our roadmap related to some uplift in the apis we use within woocommerce.

Right now the plugin supports down to WooCommerce v2.6 and PHP 5.4 — bumping the version requirements here will making using the WooCommerce SDK calls much simpler — it's possible most items that require addressing would be handled in that set of updates

**Comment by WiredWonder** [comment]
Hey Matt,

New WooCommerce stores will default to HPOS in the 2nd half of this year. For large stores such as ours, this will be an important feature to improve performance.

https://woocommerce.com/posts/platform-update-high-performance-order-storage-for-woocommerce/

It would be good to see this in the roadmap!

**Comment by matthew-muscat** [comment]
Thanks @galapogos01,

We'll be updating our plugin to ensure it is compatible with HPOS — timings of this are now locked in as yet, but we'll be ensuring we remain compatible with the new defaults while also enabling support for larger stores configured in this way

**Comment by WiredWonder** [comment]
Hey guys,

Just letting you know that WooCommerce change has happened - all new stores are created with HPOS enabled and will not work properly with Shippit. From the announcement:

> High-Performance Order Storage (HPOS) is now available to all WooCommerce stores, enabled by default for sites created on or after October 10, 2023.
> --
>  
> This long-awaited change helps our technology scale, benefiting all developers working with Woo — from extension builders to the devs who regularly maintain stores.

**Comment by matthew-muscat** [comment]
Thanks for the heads up @galapogos01 – we've already got an update in the works and currently finalising testing, expecting we'll have an update published within the next week that adds support for HPOS

**Comment by WiredWonder** [comment]
Love your work!

I have added a few features to my fork. I am not sure if any of these would be useful, but they include:

- Returning all quotes to customer with friendly name to allow carrier selection at cart/checkout
- Allow disabling shippit for certain products (eg. drop shipped or digital items)
- Performance optimisations to avoid the expensive call to Shippit's API for simple actions like add to cart or WC Admin page views (this provided major improvements) and to set a lower timeout to avoid customer & staff impact when Shippit is misbehaving
- Fix handling of Shippit initiated auto Complete (even when disabled, the Shippit webhook fires and this plugin closes the order)
- Add dutiable_amount to allow DHL International quotes to work 

I am not a pro but if you haven't already fixed these I can try to do a PR.

**Comment by matthew-muscat** [comment]
@galapogos01 — confirming HPOS is available as part of our [WooCommerce v2.0.0 release](https://github.com/Go-Shippit/Woo-Commerce/releases/tag/v2.0.0)

Additionally, some of the other items you've raised have also been addressed as part of this release
- Dutiable amounts are now communicated for all orders (https://github.com/Go-Shippit/Woo-Commerce/commit/73ed0eb657c1ef9984b75166ef5f9ed83b898948)
- The fulfillment webhook endpoint now respects the plugin settings on if this capability is enabled (https://github.com/Go-Shippit/Woo-Commerce/commit/e12e4f82946fac0f4f3f39c005046f77a2573be3)

For the remaining items you've raised, i'd suggest getting in touch with our support team so we can capture these requests/bugs and investigate them further
